print("Program Perhitungan Deret Geometri Untuk Menghitung Jumlah Suku")
a = int(input("Masukkan nilai suku pertama :"))
n = int(input("Masukkan suku yang dicari :"))
r = int(input("Masukkan rasio tiap suku :"))
un = a*r**(n-1)
print("Hasil jumlah suku ke-11 dari deret 1, 3, 9, 27, 81, ... adalah: ",un)